### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by joaocc** [yadutaf/docker-machine-driver-ovh#14]
This happens when I try to use a build based on commit 70b51ba28d911e5287e5926e3fe0814d5d4976bb.
It's accessible [here](https://github.com/joaocc/yadutaf--docker-machine-driver-ovh/releases/download/v0.5.0-joaocc-003) for convenience.

```
$ docker-machine -D create --driver ovh ccc

Docker Machine Version:  0.7.0, build a650a40
Found binary path at /usr/local/bin/docker-machine-driver-ovh
Launching plugin server for driver ovh
Plugin server listening at address 127.0.0.1:60214
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine-driver-ovh
Launching plugin server for driver ovh
Plugin server listening at address 127.0.0.1:60218
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(ccc) Calling .GetMachineName
(ccc) Calling .DriverName
(ccc) Calling .GetCreateFlags
(ccc) Calling .SetConfigFromFlags
Running pre-create checks...
(ccc) Calling .PreCreateCheck
(ccc) DBG | Validating project
(ccc) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(ccc) DBG | [signal 0xb code=0x1 addr=0x0 pc=0x21b8]
(ccc) DBG |
(ccc) DBG | goroutine 43 [running]:
(ccc) DBG | panic(0x47ce80, 0x82083c0f0)
(ccc) DBG |     /home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:464 +0x3e6
(ccc) DBG | main.(*API).GetProjects(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
(ccc) DBG |     /home/travis/gopath/src/github.com/joaocc/yadutaf--docker-machine-driver-ovh/api.go:129 +0x58
(ccc) DBG | main.(*Driver).PreCreateCheck(0x82098a1a0, 0x0, 0x0)
(ccc) DBG |     /home/travis/gopath/src/github.com/joaocc/yadutaf--docker-machine-driver-ovh/driver.go:148 +0x12c0
(ccc) DBG | github.com/joaocc/yadutaf--docker-machine-driver-ovh/vendor/github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).PreCreateCheck(0x820982100, 0x7a5648, 0x7a5648, 0x0, 0x0)
(ccc) DBG |     /home/travis/gopath/src/github.com/joaocc/yadutaf--docker-machine-driver-ovh/vendor/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:201 +0x48
(ccc) DBG | reflect.Value.call(0x43d9c0, 0x4f6998, 0x13, 0x50fd18, 0x4, 0x820969ee8, 0x3, 0x3, 0x0, 0x0, ...)
(ccc) DBG |     /home/travis/.gimme/versions/go1.6.linux.amd64/src/reflect/value.go:435 +0x120d
(ccc) DBG | reflect.Value.Call(0x43d9c0, 0x4f6998, 0x13, 0x820969ee8, 0x3, 0x3, 0x0, 0x0, 0x0)
(ccc) DBG |     /home/travis/.gimme/versions/go1.6.linux.amd64/src/reflect/value.go:303 +0xb1
(ccc) DBG | net/rpc.(*service).call(0x82097e400, 0x82097e1c0, 0x82097a1f0, 0x820987500, 0x820982820, 0x39f460, 0x7a5648, 0x16, 0x39f460, 0x7a5648, ...)
(ccc) DBG |     /home/travis/.gimme/versions/go1.6.linux.amd64/src/net/rpc/server.go:383 +0x1c2
(ccc) DBG | created by net/rpc.(*Server).ServeCodec
(ccc) DBG |     /home/travis/.gimme/versions/go1.6.linux.amd64/src/net/rpc/server.go:477 +0x49d
Error with pre-create check: "unexpected EOF"
open : no such file or directory
notifying bugsnag: [Error with pre-create check: "unexpected EOF"]
```

**Comment by yadutaf** [comment]
I believe this duplicates #13. If it does not, please feel free to re-open.

**Comment by yadutaf** [comment]
This is actually distinct from #13. This issue concerns error detection/reporting in the pre-check phase of the driver while #13 is related to an older version. Hence this issue is the issue to fix. I was too fast...

**Comment by yadutaf** [comment]
OK, that's _much_ better with a message like:

``` console
$ docker-machine -D create --driver ovh bbb
...
Running pre-create checks...
(bbb) Calling .PreCreateCheck
Error with pre-create check: "Could not create a connection to OVH API. You may want to visit: https://github.com/yadutaf/docker-machine-driver-ovh#example-usage. The original error was: Missing application key. Please check your configuration or consult the documentation to create one."
open : no such file or directory
notifying bugsnag: [Error with pre-create check: "Could not create a connection to OVH API. You may want to visit: https://github.com/yadutaf/docker-machine-driver-ovh#example-usage. The original error was: Missing application key. Please check your configuration or consult the documentation to create one."]
```

Thanks for pointing it out.
